import { useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { Col, Row, Container } from "react-bootstrap";
import { useContext } from "react";
import { DataContext } from "../store/GlobalState";
const Home = () => {
  const router = useRouter();
  const { state, dispatch } = useContext(DataContext);
  useEffect(() => {
    dispatch({
      type: "NAVBAR",
      payload: true,
    });
  }, []);
  return (
    <div id="home">
      <Head>
        <title>DashBoard</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-center pb-3">Dashboard</h1>

      {/* calender */}
      <div className="bg-white sticky-top">
        <Container>
          <Row className="pb-3 pt-3 mb-4">
            <Col className="">
              <div className="d-flex justify-content-between text-muted">
                <div className="date-container">
                  <span>Mon</span>
                  <span className="date">6</span>
                </div>
                <div className="date-container">
                  <span>TUE</span>
                  <span className="date">7</span>
                </div>
                <div className="date-container">
                  <span>WED</span>
                  <span className="date">8</span>
                </div>
                <div className="date-container">
                  <span>THU</span>
                  <span className="date">9</span>
                </div>
                <div className="date-container">
                  <span>FRI</span>
                  <span className="date">10</span>
                </div>
                <div className="date-container">
                  <span>SAT</span>
                  <span className="date">11</span>
                </div>
                <div className="date-container">
                  <span>SUN</span>
                  <span className="date">12</span>
                </div>
              </div>
            </Col>
          </Row>
        </Container>
      </div>

      {/* earning today */}
      <Container>
        <Row className="mb-4">
          <Col>
            <div className="shadow round py-4 px-3">
              <Row>
                <Col>
                  <div className="d-flex flex-column">
                    <span className="fs-5 fw-bold mb-3">Earnings Today</span>
                    <span className="fs-3 fw-bolder mb-1">$768</span>
                    <span className=" text-muted">($642 Yesterday)</span>
                  </div>
                </Col>

                <Col className="d-flex justify-content-center">
                  <Row className="w-100">
                    <Col xs={12}>
                      <p className="text-center">graph</p>
                    </Col>

                    <Col className="d-flex justify-content-end align-items-end">
                      <span className="primary pointer pt-3 ps-3">
                        View Details
                      </span>
                    </Col>
                  </Row>
                </Col>
              </Row>
            </div>
          </Col>
        </Row>

        {/* current orders */}
        <Row className="mb-4">
          <Col xs={6} md={4}>
            <div className="d-flex flex-column align-items-center justify-content-center w-100 py-4 round bg-black h-100">
              <span className="fs-1 fw-bold text-white">12</span>
              <span className="fw-bold text-white">New Orders</span>
            </div>
          </Col>
          <Col xs={6} md={8}>
            <Row>
              <Col xs={12} md={6}>
                <div className="d-flex flex-column align-items-center justify-content-center shadow py-4 round">
                  <span className="fs-1 text-warning fw-bold">12</span>
                  <span className="fw-bold">Open Orders</span>
                </div>
              </Col>
              <Col xs={12} md={6}>
                <div className="d-flex flex-column align-items-center justify-content-center shadow py-4 round">
                  <span className="fs-1 text-success fw-bold">12</span>
                  <span className="fw-bold">Closed Orders</span>
                </div>
              </Col>
            </Row>
          </Col>
        </Row>

        {/* manage menu */}
        <Row className="mb-5">
          <Col>
            <div className="shadow round px-4 py-3">
              <Row>
                <Col>
                  <div className="">image</div>
                </Col>

                <Col className="d-flex flex-column">
                  <span className="fw-bold mt-4 mb-2">Manage Menu</span>
                  <span className="mb-3">
                    Check the items available in your menu card
                  </span>
                  <Row>
                    <Col xs={8} md={5}>
                      <button
                        className="btn w-100 mb-5"
                        onClick={() => router.push("/menu")}
                      >
                        Add items
                      </button>
                    </Col>
                  </Row>
                </Col>
              </Row>
            </div>
          </Col>
        </Row>
      </Container>
    </div>
  );
};

export default Home;
