import { useState, useEffect } from "react";
import Aos from "aos";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";

import { useContext } from "react";
import { DataContext } from "../store/GlobalState";
import AboutUs from "../components/AboutUs";
import TermCondition from "../components/TermCondition";
export default function Home() {
  const router = useRouter();
  const { state, dispatch } = useContext(DataContext);
  const [loginToggle, setloginToggle] = useState(false);

  useEffect(() => {
    Aos.init({ duration: 1500, once: true, offset: 20 });
  }, []);

  useEffect(() => {
    dispatch({
      type: "NAVBAR",
      payload: false,
    });
  }, []);
  const landingComtent = () => {
    return (
      <div className="d-flex flex-column align-items-center">
        {" "}
        <div className="text-container my-3 mb-4">
          <p className="text-center m-1 text-white" data-aos="fade-left">
            Find your perfect place for eat, meet
          </p>
          <p
            className="text-center m-1 text-white"
            data-aos="fade-right"
            data-aos-delay="300"
          >
            and get rewards
          </p>
        </div>
        <button
          className="btn w-100"
          data-aos="fade"
          data-aos-delay="500"
          onClick={() => router.push("/login")}
        >
          <a>Get Started</a>
        </button>
        <div className="mt-3" data-aos="fade" data-aos-delay="800">
          <span className="text-white">start your day</span>
          <span
            className="login-btn p-1 py-2"
            onClick={() => setloginToggle(!loginToggle)}
            // onClick={() => router.push("/login")}
          >
            {" "}
            Login
          </span>
        </div>
      </div>
    );
  };

  const loginComponent = () => {
    return (
      <div style={{ background: "white" }} className="d-flex flex-column">
        <label className="custom-field">
          <input type="text" required />
          <span className="placeholder">placeholder</span>
        </label>
        <label className="custom-field">
          <input type="password" required />
          <span className="placeholder">placeholder</span>
        </label>
      </div>
    );
  };

  return (
    <div id="index">
      <Head>
        <title>Brud Rewards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="background-container d-flex align-items-center position-relative">
        <div className="cover position-absolute"></div>
        <img src="../background.png" alt="" />
      </div>

      <div className="body d-flex align-items-center justify-content-center py-2">
        <div className="body-container mx-4 d-flex flex-column align-items-center">
          <div className="logo-container position-relative">
            {/* <Image
              data-aos="zoom-in"
              src="/logo.png"
              alt="Logo"
              layout="responsive"
              width={7337}
              height={4920}
              // loading="eager"
              priority={true}
            /> */}
            <img
              data-aos="zoom-in"
              src="/logo.png"
              alt="Logo"
              style={{ width: "100%" }}
            />
          </div>
          {/* {loginToggle ? loginComponent() : landingComtent()} */}

          {landingComtent()}

          <footer className="d-flex mt-5">
            <AboutUs className="px-2" />
            <TermCondition />
          </footer>
          {/* <div className="d-flex flex-column justify-content-center align-items-center">
            <div className="text-container my-3 mb-4">
            <p className="text-center m-1" data-aos="fade-left">
            Find your perfect place for eat, meet
            </p>
            <p
            className="text-center m-1"
            data-aos="fade-right"
            data-aos-delay="300"
            >
            and get rewards
            </p>
         
            </div>

            <button
              className="btn w-100"
              data-aos="fade"
              data-aos-delay="500"
              onClick={() => router.push("/login")}
            >
              <a>Get Started</a>
            </button>
            <div className="mt-3" data-aos="fade" data-aos-delay="800">
              <span>start your day</span>
              <span
                className="login-btn p-1 py-2"
                onClick={() => router.push("/login")}
              >
                {" "}
                Login
              </span>
              </div>
          </div> */}
        </div>
        <div />
      </div>

      {/* <footer></footer> */}
    </div>
  );
}
